services:
  app:
    build: .
    ports:
      - "8080:1323"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/database?sslmode=disable
      PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDgeU4Zff4dpBHN\n0FyWT4Yg2EtsBjRfsl2GbZulVc3On/SaPE8rquoqEofxB2q9HV5IM5gFtEl27vGS\nBY8psJhZurUrrm4IhgUQV+10kpyC0Z3EZXLal0eEGcqhW88vwMcgBy7SL5ylMz0/\nl3nliUDR7MhTjPQhV47WdFJCne/NWkzv4FS1D4zennmmbwKdu4vr3fYIfjL2WBBZ\nmXnd4SxNkYD5Qtze4T+R2svTEJv+SbBRfzxOpURrQUncn+BYd2n3UI1CP/eXUAjQ\niKmkExSlkzhiJvszmE+if2lke1WiBMo/H5WYBw0hQd3O/VlVUKxrTVrBhdWCihbX\njGkqGlsZAgMBAAECggEBAK2oiugj1cz+mht8f7R1b1HHo4m9vxTtu3b9IvWkzOR2\nUNhloeYpgqDr1yl70HLf3onDCHAZSuBs+Iw8KsZY7XQ1gmV5u3xymkZLj9OofNaj\n7gb7aQB9GoGzJlTw3veVjzdS90D6Pph7bH3e5RnTtkbxhQVGPbPxtfpo4R7SaquV\nJpZQGnnFaYATecAeIyIo30PqtQ5AuzSQ8801w4mKW5NXt+cItXiCrRQ9QfbAKAqs\nRgdIExKsjaWwoo1YL84kWo5H4xwB0G+HtSg9DLWl4yy83S3p559jf9JV/+4v471Z\nlX58kCOioHGHo12mq+hVgIJCyN+t/6M0E5yIFzhViQECgYEA8ZJyPRfOu8FTsjE7\ntKh8RLs/ITvnpnDZl5zYpUeJw6BKptEklcREYj+OvVNJ5jVvjHjJFtkohuKMPqZL\nsodWcWp3+cXKbtlftwaG95nJWjjOxyZhqbAm/035EPX86V10OccebSLiwfSoCvHm\nugYONTJGFQtI4E0BSA7W0B0qu2ECgYEA7eFu4D1+2FPIhomA/EAL0HvrYJ32+fYq\nllXAZcAiYF9XObwFjeSM1I+/1DYESUhwYsWj3xbghrqJU5Zzs0+yUF4t0J4Tv7iX\nRfBZamiYGRBpfHv3TD7iQ3h9wBX+AG4+imthlvlEAJYk47n9uhSbHtuUyS0Bm5rV\nRh/DqUGgMrkCgYEAqS6RByxHQsMwpJlKYUmmTlR87/+OSsi5+y6Do60oVHNMFOxg\nHOtpoQ02IG3WUX2W8+AbpP7NHTpIUhAQ76VM6v1PrQPStDNUj0/o8jsoAyHJ3zuI\nJlkR1rd6+V/tklo67cQAERrfiEqZ7aBgoGNhS+w7nL1ceooznY2W8AWdScECgYAd\nWKNKDKwaWfOyDUKZW/lZJgB6seInIiRM2ZVbuCFFjF2BZN22jIyHKJi8wFE1DTe4\nJ7O4sOTQGjEY28W4SEuyOHwkcWv0Sfx3h1gwlWi2Jt0sm0p94IAfXLz+tnfYa8FR\naD/o1SV7gQpaAbb4ftRIMUSgsOmy3Z4UAZUsy0jNGQKBgQCSUqe6jbMDPytKJZyC\nL89sEGLAbM3fWa1Ij+R+n99KrvNitNP2kRO/RI4b0i+T0Xu3Qu8S8hMMQt4dwKQm\nWr5PPw3WFc5zGaT+II4zTEvcsMzxyZjUmEn5Zbvue4CaPSK2/LZfTAxtvS5a4+9w\nxvvEDxFfaCYsCirtCs6kXuERow==\n-----END PRIVATE KEY-----\n"
    depends_on:
      db:
        condition: service_healthy
  db:
    platform: linux/x86_64
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
      # Load database schema from ./database.sql
      # If you want to reload new database schema, you need to execute
      # `docker-compose down --volumes` first to remove the volume.
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  db:
    driver: local
